# Generated by Django 5.0.6 on 2024-06-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="The Grumpy OCI Engineer", max_length=255),
        ),
    ]
