# Generated by Django 5.0.6 on 2024-06-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theblog", "0002_post_title_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title_tag",
            field=models.CharField(
                default=models.CharField(max_length=255), max_length=255
            ),
        ),
    ]
