# Generated by Django 5.0.6 on 2024-06-27 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theblog", "0003_alter_post_title_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="title_tag",
        ),
    ]
