# Generated by Django 5.0.6 on 2024-07-01 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theblog", "0004_remove_post_title_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pub_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
